# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱名')),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(default=' ', max_length=20, verbose_name='用户名')),
                ('icon', models.CharField(default=' ', max_length=40)),
                ('token', models.CharField(default=' ', max_length=256)),
            ],
        ),
    ]
