# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('smallimg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mgj_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('identifier', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'mgj_order',
            },
        ),
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('smallImg1', models.CharField(max_length=100)),
                ('smallImg2', models.CharField(max_length=100)),
                ('smallImg3', models.CharField(max_length=100)),
                ('smallImg4', models.CharField(max_length=100)),
                ('oldprice', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('store', models.IntegerField()),
                ('sales', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mgj_goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱名')),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(default=' ', max_length=20, verbose_name='用户名')),
                ('icon', models.CharField(default=' ', max_length=40)),
                ('token', models.CharField(default=' ', max_length=256)),
            ],
            options={
                'db_table': 'mgj_user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
