# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='mgj_user',
        ),
    ]
