# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='smallimg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
