# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='mgj_cart',
        ),
    ]
