# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181213_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
